### ISSUE TITLE
拖拽本地图片报错 “upload error”

### ISSUE THREAD

**Issue by jinzhao-data** [renmu123/obsidian-image-auto-upload-plugin#160]
在使用 本地图片拖拽到 obsidian当中，会报错，“upload error”

1. picgo 在独立上传图片，没有问题，排除picgo自身的问题
2. 用微信截图，ctr v 到obsidian 的情况下是可以上传图床的。

工作需要在本地上传图片，辛苦看一下什么问题。
或者告诉我如何查看错误日志。

**Comment by renmu123** [comment]
请先提供更多信息，比如ob版本，插件版本，系统

**Comment by jinzhao-data** [comment]
obsidian版本：v1.7.6
image aotu upload:4.0.0
picgo:2.4.0 beta
picgo log:
2024-11-18 12:06:16 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of null (reading 'startsWith')
    at se (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:2008)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:41422
    at Array.map (<anonymous>)
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:41329)
    at je.doTransform (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19338)
    at je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18563)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74893)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690047)
-------Error Stack End------- 
2024-11-18 12:06:16 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by renmu123** [comment]
你用得是beta几呢？系统是什么？

请尝试升级到最新的beta版本或者使用最新得正式版picgo

**Comment by jinzhao-data** [comment]
picgo用的2.4.0 beta8，因为我用的最新的稳定版升到2.4.0 beta8的，都有这个问题。系统是mac os 15.0.1 
![image](https://github.com/user-attachments/assets/14578e57-8805-4909-83d9-59a73aa481fc)，

obsidian console 的是：
![image](https://github.com/user-attachments/assets/8309dac2-6923-4391-8a38-c16bdb60cb7e)

**Comment by renmu123** [comment]
我手上没有Mac，没法进行debug

**Comment by cecech** [comment]
遇到了同样的问题...

**Comment by zero617** [comment]
windows 
obsidian v1.7.6
piclist v2.9,4
也同样的问题

**Comment by Jett191** [comment]
------Error Stack Begin------
TypeError: Cannot read properties of null (reading 'startsWith')

拖拽上传的问题出在 PicGo 收到了一个无效的请求，其中 {"list":[null]} 是关键问题。正常情况下，拖拽上传应该传递一个有效的文件路径，但这里显示路径为空（null），导致 startsWith 方法无法调用

**Comment by renmu123** [comment]
[ob](https://obsidian.md/changelog/2024-11-04-desktop-v1.7.5/) 在1.7.5版本，升级为了[electron 32](https://www.electronjs.org/zh/blog/electron-32-0)，32版本移除了拖拽时获取文件路径，所以无法获取路径，也无法上传成功。
临时解决方案，可以降级到ob 1.7.4版本，然后利用内部的更新机制来进行更新，而非手动安装最新安装包。

由于后续版本会对手机端进行兼容，将全部采用ob的兼容api，picgo能不能做这个功能有待测试，如果是piclist用户可以开启远程模式解决

**Comment by specialhua** [comment]
archlinux降级1.7.4版本后拖拽上传没问题了，期待更新后兼容。谢谢

**Comment by renmu123** [comment]
fix in https://github.com/renmu123/obsidian-image-auto-upload-plugin/commit/eb5108ef3f4fa6540fe1e7c804a6abb344c0b6f8   由于使用了electron专有api，无法保证在之后的手机兼容版本依然支持
