### ISSUE TITLE
批量上传出错 PicGo找不到对象

### ISSUE THREAD

**Issue by Tony84** [renmu123/obsidian-image-auto-upload-plugin#29]
PicGo给了出错信息 【WIN10+Obsidian V0.14.6 + image auto upload 2.0.3】
Error: image not found in clipboard
    at PicGo.upload (C:\Users\------\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:180:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Object.upload (C:\Users\---------\AppData\Local\Programs\PicGo\resources\app.asar\background.js:36:29196)
    at async Bt (C:\Users\---------\AppData\Local\Programs\PicGo\resources\app.asar\background.js:36:30882)
    at async C:\Users\-----------\AppData\Local\Programs\PicGo\resources\app.asar\background.js:36:32415

不知道能否加上 上传后将图片本地地址更改为新生成的图床链接。

**Comment by renmu123** [comment]
这个报错是没有找到任何图片，你图片的格式是 `![]()` 这种的吗？

**Comment by renmu123** [comment]
https://github.com/renmu123/obsidian-image-auto-upload-plugin/issues/21

**Comment by Tony84** [comment]
是的，试验了两种，如下，单独上传（右键选upload）- 都可以上传。命令行里 upload all 没有反应：

[![X](mmm.jpg)
 ![[Pasted image 20210915134005.png]]

**Comment by allworldg** [comment]
uploadall可以直接更新连接，要是手动上传单个也能自动更新链接就更好了

**Comment by five-five0909** [comment]
obsidan0.14.6+pic2.3.0+win10，上传报错，作者大大
    at PicGo.upload (F:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:180:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Object.upload (F:\Program Files\PicGo\resources\app.asar\background.js:36:29196)
    at async Bt (F:\Program Files\PicGo\resources\app.asar\background.js:36:30882)
    at async F:\Program Files\PicGo\resources\app.asar\background.js:36:32415

**Comment by renmu123** [comment]
#32
